import matplotlib.pyplot as plt

# EXAMPLE
# Data from https://tylervigen.com/spurious-correlations

years = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]

# Number of CS doctorates awarded in the US each year
cs_doctorates = [861, 830, 809, 867, 948, 1125, 1455, 1656, 1787, 1611]

# Plot CS doctorates by year and save it to the file cs_doctorates.png
plt.plot(years, cs_doctorates)
plt.title('CS Doctorates')
plt.xlabel('Years')
plt.ylabel('Count')
plt.savefig("cs_doctorates")
plt.close()

# Total revenue generated by arcades in the US each year, in billions
arcade_revenue = [1.196, 1.176, 1.269, 1.240, 1.307, 1.435, 1.601, 1.654, 1.803, 1.734]

# Plot Arcade revenue by year and save it to the file cs_doctorates.png
plt.plot(years, arcade_revenue)
plt.title('Arcade Revenue')
plt.xlabel('Years')
plt.ylabel('Revenue (billions)')
plt.savefig("arcade_revenue")
plt.close()
